# Initial config based on boton deployment (should be reproducible, for same RSKJ pvt key)
# contents copied over initially from docs/regtest

[[pairs]]
base = "LTC"
quote = "BTC"
fee = 2
timeoutDelta = 400

[[pairs]]
base = "BTC"
quote = "BTC"
rate = 1
fee = 0.5
timeoutDelta = 1_440

[[pairs]]
base = "LTC"
quote = "LTC"
rate = 1
fee = 0.5
timeoutDelta = 1_440

[[pairs]]
base = "ETH"
quote = "BTC"
fee = 5
timeoutDelta = 180

# todo(shree) switch this to rDOC
[[pairs]]
base = "BTC"
quote = "USDT"
fee = 5
timeoutDelta = 180

[[currencies]]
symbol = "BTC"
network = "bitcoinRegtest"
minWalletBalance = 10_000_000
minChannelBalance = 10_000_000
maxSwapAmount = 4_294_967
minSwapAmount = 10_000
maxZeroConfAmount = 10_000_000

  [currencies.chain]
  host = "127.0.0.1"
  port = 18_443
  cookie = "docker/regtest/data/core/cookies/.bitcoin-cookie"
  rpcuser = "kek"
  rpcpass = "kek"

  [currencies.lnd]
  host = "127.0.0.1"
  port = 10_009
  certpath = "docker/regtest/data/lnd/certificates/tls.cert"
  macaroonpath = "docker/regtest/data/lnd/macaroons/admin.macaroon"

[[currencies]]
symbol = "LTC"
network = "litecoinRegtest"
minWalletBalance = 110_000_000
minChannelBalance = 110_000_000
maxSwapAmount = 2000_000_000
minSwapAmount = 100_000
maxZeroConfAmount = 0

  [currencies.chain]
  host = "127.0.0.1"
  port = 19_443
  cookie = "docker/regtest/data/core/cookies/.litecoin-cookie"
  rpcuser = "kek"
  rpcpass = "kek"

  [currencies.lnd]
  host = "127.0.0.1"
  port = 11_009
  certpath = "docker/regtest/data/lnd/certificates/tls.cert"
  macaroonpath = "docker/regtest/data/lnd/macaroons/admin.macaroon"

[ethereum]
# providerEndpoint = "http://127.0.0.1:8546" -> original used geth with ws (8546), witch to http 4444 
providerEndpoint = "http://127.0.0.1:4444"

# these addresses are from initial boton deployment
etherSwapAddress = "0x77045E71a7A2c50903d88e564cD72fab11e82051"
erc20SwapAddress = "0xDA7Ce79725418F4F6E13Bf5F520C89Cec5f6A974"

  [[ethereum.tokens]]
  symbol = "ETH"

  maxSwapAmount = 4_294_96700
  minSwapAmount = 10000

  # todo(shree) switch this to rDOC
  # for regtest mode, use address of ERC20 token address (boton)
  [[ethereum.tokens]]
  symbol = "USDT"
  decimals = 18
  contractAddress = "0x83C5541A6c8D2dBAD642f385d8d06Ca9B6C731ee"

  maxSwapAmount = 4_294_96700000
  minSwapAmount = 10000

